name: CI

on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Run one-line script
      run: echo Hello, world!
    
    - name: Run a multi-line script
      run: |
        echo add other action to build,
        echo test snd deployyour project
    

 
  
